server:
  port: 8093
  servlet:
    contextPath: /wave

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: create
    hibernate:
      use-new-id-generator-mappings: false
  datasource:
    url: jdbc:mysql://localhost:3306/world
    username: root
    password: P@ssword







